// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixilnyijhukzdtxkuzmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4aWxueWlqaHVremR0eGt1em14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDAwODIsImV4cCI6MjA1ODY3NjA4Mn0.klCbz1hz3e5YsjEY7dapV8prcKSK4-sIG5UEMh5xQBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);